stages:
  - check
  - test

checkstyle-frontend:
  image: node:latest
  stage: check
  script:
    - cd frontend
    - npm install
    - npm install standard
    - npm install jest
    - npx standard --global test --global expect .
    - if [[ $? -eq 0 ]]; then echo "JS Linter did not find any issues."

frontend-test:
  image: node:latest
  stage: test
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test
  only:
    refs:
      - merge_requests
