stages:
  - check
  - test

checkstyle-frontend:
  image: node:latest
  stage: check
  script:
    - cd frontend
    - npm install
    - npm install standard
    - standard

frontend-test:
  image: node:latest
  stage: test
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test
  only:
    refs:
      - merge_requests
