stages:
  - check
  - build  
  - test

checkstyle-backend:
  image: python:3.11-alpine
  stage: check
  script:
    - apk add --no-cache git
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv install
    - pipenv run codestyle
    - pipenv --rm


backend-build:
  image: python:3.11-alpine
  stage: build
  script:
    - apk add --no-cache git
    - pip install --upgrade pip
    - pip install pipreqs
    - pip install pipenv
    - pipenv install
    - pipenv run cd ./backend
    - pipenv run pipreqs --force .
    - pipenv run manage.py makemigrations
    - pipenv run manage.py migrate
    - pipenv run manage.py check
    - pipenv --rm

backend-test:
  image: python:3.11-alpine
  stage: test
  script:
    - apk add --no-cache git
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv install
    - pipenv run pytests
    - pipenv --rm
  # only:
  #   refs:
  #     - merge_requests
