stages:
  - build  
  - check
  - test

checkstyle-backend:
  image: python:3.11-alpine
  stage: check
  script:
    - apk add --no-cache git
    - pip install --upgrade pip
    - pip install pycodestyle
    - pip install pipenv
    - pipenv install
    - pipenv run pycodestyle
    - pipenv --rm


backend-build:
  image: python:3.11-alpine
  stage: build
  script:
    - apk add --no-cache git
    - pip install --upgrade pip
    - pip install pipreqs
    - pip install pipenv
    - pipenv install
    - cd ./backend
    - pipenv run pip install pymongo
    - pipenv run pipreqs --force ..
    - pipenv run ./manage.py makemigrations
    - pipenv run ./manage.py migrate
    - pipenv run ./manage.py check
    - pipenv --rm


backend-test:
  image: python:3.11-alpine
  stage: test
  script:
    - apk add --no-cache git
    - apk update
    - apk add make automake gcc g++ subversion python3-dev
    - pip install --upgrade pip
    - pip3 install pipenv
    - pipenv install
    - pipenv run pip3 install -r ./requirements.txt
    - cd ./backend
    - pipenv run pytests
    - pipenv --rm

  only:
    refs:
      - merge_requests
