stages:
  - check
  - build  
  - test

checkstyle-backend:
  image: python:3.11-alpine
  stage: check
  script:
    - apk add --no-cache git # allows to not cache the index locally, which is useful for keeping containers small.
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv install
    - pipenv run codestyle


backend-build:
  image: python:3.11-alpine
  stage: build
  script:
    - apk add --no-cache git
    - pip install --upgrade pip
    - pip install pipenv
    - pip install pipreqs
    - pipenv install
    - pipenv run reqs & make & migrate & check

backend-test:
  image: python:3.11-alpine
  stage: test
  script:
    - apk add --no-cache git
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv install
    - pipenv run pytests
  # only:
  #   refs:
  #     - merge_requests
